package constants

var COMPANIES = []string{"Google", "Microsoft", "Amazon", "Uber", "Tiger Analytics", "persistent systems", "Facebook", "IMC", "Wealthfront", "Arista Networks", "MindTree", "FPT", "zeta suite", "payu", "Bloomberg", "Cognizant", "Zoho", "Goldman Sachs", "Wayfair", "Canonical", "Karat", "instacart", "Accenture", "Grab", "Jane Street", "Quora", "Zopsmart", "Twitter", "Postmates", "Salesforce", "Commvault", "Info Edge", "tiktok", "razorpay", "Pinterest", "Sprinklr", "PhonePe", "Apple", "Deutsche Bank", "Walmart Global Tech", "Booking.com", "Jeavio", "T System", "Cisco", "Expedia", "Optum", "ByteDance", "Citrix", "TIAA", "Bolt", "Adobe", "MakeMyTrip", "Moengage", "Rakuten", "Netflix", "eBay", "Capital One", "Honeywell", "Dropbox", "JPMorgan", "Docusign", "tcs", "Softwire", "DoorDash", "HRT", "Virtu Financial", "Tesla", "Snapchat", "AppDynamics", "Duolingo", "AllinCall", "edabit", "Robinhood", "LinkedIn", "Flipkart", "Cashfree", "Toptal", "Dunzo", "APT Portfolio", "Pure Storage", "Spotify", "Sumologic", "Oracle", "Twilio", "C3 IoT", "Morgan Stanley", "JP Morgan", "peak6", "Indeed", "Mercari", "Arcesium", "IBM", "DJI", "Rupeek", "Directi", "Yandex", "Netsuite", "Nuro", "Roblox", "DRW", "American Express", "Yahoo", "Samsung", "VMware", "United Health Group", "Yelp", "Sony", "OT", "Visa", "Qualtrics", "Akuna Capital", "Atlassian", "Coursera", "Square", "DE Shaw", "Infosys", "Cruise Automation", "SAP", "Two Sigma", "Airbnb", "Palantir Technologies", "Paypal", "ZScaler", "Rubrik", "Intuit", "PayTM", "Nvidia", "Citadel", "ServiceNow", "Druva", "Nutanix", "Lyft", "Asana", "Thumbtack", "Akamai", "MindTickle", "Qualcomm", "IIT Bombay", "Hotstar", "HBO", "Zoom", "Swiggy", "Drawbridge", "Epic Systems", "TripleByte", "Activision", "Athenahealth", "Mathworks", "Alibaba", "Valve", "IXL", "Opendoor", "Works Applications", "Tencent", "Gilt Groupe", "Pocket Gems", "LiveRamp", "Baidu", "Riot Games", "Leap Motion", "MAQ Software", "Affirm", "Redfin", "Hulu", "Wish", "Twitch", "GoDaddy", "BlackRock", "Databricks", "Intel", "Shopee", "Cohesity", "Alation", "Zenefits", "FactSet", "Box", "TuSimple", "Reddit", "Zillow", "National Instruments", "Sapient", "Splunk", "Barclays", "Dataminr", "Huawei", "Dell", "Zomato"}
var TOPICS = map[string]int{
    "Array": 1815,
    "String": 754,
    "Hash Table": 658,
    "Dynamic Programming": 558,
    "Math": 548,
    "Sorting": 429,
    "Greedy": 394,
    "Depth-First Search": 309,
    "Database": 295,
    "Binary Search": 294,
    "Matrix": 244,
    "Tree": 239,
    "Breadth-First Search": 237,
    "Bit Manipulation": 231,
    "Two Pointers": 214,
    "Prefix Sum": 186,
    "Heap (Priority Queue)": 184,
    "Binary Tree": 176,
    "Simulation": 169,
    "Stack": 165,
    "Graph": 156,
    "Counting": 154,
    "Sliding Window": 142,
    "Design": 128,
    "Backtracking": 106,
    "Enumeration": 103,
    "Union Find": 86,
    "Linked List": 79,
    "Ordered Set": 67,
    "Number Theory": 66,
    "Monotonic Stack": 63,
    "Segment Tree": 54,
    "Trie": 54,
    "Bitmask": 48,
    "Divide and Conquer": 47,
    "Combinatorics": 46,
    "Queue": 46,
    "Recursion": 46,
    "Binary Indexed Tree": 41,
    "Geometry": 40,
    "Binary Search Tree": 40,
    "Hash Function": 39,
    "Memoization": 39,
    "String Matching": 34,
    "Topological Sort": 33,
    "Shortest Path": 32,
    "Rolling Hash": 30,
    "Game Theory": 28,
    "Interactive": 23,
    "Data Stream": 21,
    "Monotonic Queue": 17,
    "Brainteaser": 17,
    "Randomized": 12,
    "Merge Sort": 12,
    "Doubly-Linked List": 11,
    "Counting Sort": 9,
    "Iterator": 9,
    "Concurrency": 9,
    "Probability and Statistics": 7,
    "Quickselect": 7,
    "Suffix Array": 7,
    "Bucket Sort": 6,
    "Minimum Spanning Tree": 5,
    "Line Sweep": 5,
    "Shell": 4,
    "Reservoir Sampling": 4,
    "Strongly Connected Component": 3,
    "Eulerian Circuit": 3,
    "Radix Sort": 3,
    "Rejection Sampling": 2,
    "Biconnected Component": 1,
}